---
title: "One Food risk tool"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "#ffffff"
      fg: "#0c2357" 
      primary: "#006e8c"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(readxl)
library(here)
library(data.table)
library(DT)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
```

Introduction
================================================================================

Column
--------------------------------------------------------------------------------
#### One Food project

#### One Food risk tool

The One Food risk tool maintainer is Sarah Alewijnse (Cefas).
Please email sarah.alewijnse@cefas.gov.uk for debugging assistance.

Hazard and sector selection {data-navmenu="Risk score template" data-icon="fa-square-check"}
================================================================================

Column {data-width=250}
--------------------------------------------------------------------------------

#### Sector selection

```{r}
checkboxGroupInput(inputId = "template_sector",
                   label = "Sector",
                   choices = c("Aquaculture",
                               "Capture Fisheries",
                               "Crops",
                               "Terrestrial Livestock",
                               "Wild Foraging"))
```

Column {data-width=650 .tabset}
--------------------------------------------------------------------------------

#### Hazard selection

### Biological

```{r}
checkboxGroupInput(inputId = "template_haz_bio",
                   label = "Biological hazards",
                   choices = c("Pathogens - Fungal",
                               "Pathogens - Bacterial",
                               "Pathogens - Viral",
                               "Pathogens - Protistan",
                               "Weeds",
                               "Pests - Arthropods",
                               "Pests - Helminths",
                               "Pests - Molluscs",
                               "Human-wildlife conflict",
                               "Harmful algal blooms",
                               "Extraction of wild organisms",
                               "Biodiversity loss",
                               "Range shifts",
                               "Invasive non-native species",
                               "Genetically modified organisms"))
```

### Chemical

```{r}
checkboxGroupInput(inputId = "template_haz_chem",
                   label = "Chemical hazards",
                   choices = c("Pesticides",
                               "Herbicides",
                               "Antimicrobials",
                               "Antihelminthics",
                               "NPKS fertlisers",
                               "Poor soil chemistry",
                               "Methanogenesis",
                               "Heavy metals",
                               "Salinity incursions",
                               "Disinfectants",
                               "Plastics - Food production",
                               "Air pollution",
                               "Radiological contamination",
                               "Chemical spillages",
                               "Ocean acidification",
                               "Hypoxia",
                               "Refrigeration",
                               "Carbon dioxide emissions",
                               "E-waste"))
```

### Physical

```{r}
checkboxGroupInput(inputId = "template_haz_phys",
                   label = "Physical hazards",
                   choices = c("Water scarcity",
                               "Flooding",
                               "Temperature",
                               "Extreme temperatures",
                               "Storms",
                               "Wildfires",
                               "Noise and light pollution",
                               "Tillage",
                               "Soil erosion and compaction",
                               "Destructive fishing practices",
                               "Food waste - Unavoidable",
                               "Food packaging",
                               "Mis-sold goods",
                               "Land use change"))
```

### Socio-economic

```{r}
checkboxGroupInput(inputId = "template_haz_soc",
                   label = "Socio-economic hazards",
                   choices = c("Reduced labour force",
                               "Food waste - Avoidable",
                               "Population growth",
                               "Food production costs",
                               "Human disease",
                               "Human conflict",
                               "Lack of knowledge",
                               "Access to veterinary services",
                               "Dietary changes",
                               "Land rights",
                               "Energy policies",
                               "Food subsidies"))
```

Data template download {data-navmenu="Risk score template" data-icon="fa-file-excel"}
================================================================================

Column {data-width=650}
--------------------------------------------------------------------------------

#### View template

```{r}
# Base template ----------------------------------------------------------------
template_data <- data.frame(Category = NA,
                            Hazard = NA,
                            Impact = NA,
                            Sector = NA,
                            Score = NA)

# Create template from inputs
template_data <- reactive({
  # Biological
  ifelse(length(input$template_haz_bio) > 0,
         biological_template <- data.frame(Category = rep("Biological", 
                                                          length(input$template_haz_bio) * length(input$template_sector)),
                                           Hazard = rep(input$template_haz_bio,
                                                        length(input$template_sector)),
                                           Sector = sort(rep(input$template_sector,
                                                             length(input$template_haz_bio))),
                                           Scores = NA),
         biological_template <- data.frame(Category = NULL,
                                           Hazard = NULL,
                                           Sector = NULL,
                                           Scores = NULL))
  
  # Chemical
  ifelse(length(input$template_haz_chem) > 0,
         chemical_template <- data.frame(Category = rep("Chemical", length(input$template_haz_chem)),
                                    Hazard = input$template_haz_chem,
                                    Sector = sort(rep(input$template_sector,
                                                 length(input$template_haz_chem))),
                                    Scores = NA),
         chemical_template <- data.frame(Category = NULL,
                                    Hazard = NULL,
                                    Sector = NULL,
                                    Scores = NULL))
  
  # Physical
  ifelse(length(input$template_haz_phys) > 0,
         physical_template <- data.frame(Category = rep("Physical", length(input$template_haz_phys)),
                                    Hazard = input$template_haz_phys,
                                    Sector = sort(rep(input$template_sector,
                                                 length(input$template_haz_phys))),
                                    Scores = NA),
         physical_template <- data.frame(Category = NULL,
                                    Hazard = NULL,
                                    Sector = NULL,
                                    Scores = NULL))
  
  # Socio-economic
  ifelse(length(input$template_haz_soc) > 0,
         socio_economic_template <- data.frame(Category = rep("Socio-economic", length(input$template_haz_soc)),
                                    Hazard = input$template_haz_soc,
                                    Sector = sort(rep(input$template_sector,
                                                 length(input$template_haz_soc))),
                                    Scores = NA),
         socio_economic_template <- data.frame(Category = NULL,
                                    Hazard = NULL,
                                    Sector = NULL,
                                    Scores = NULL))
  rbind(biological_template,
        chemical_template,
        physical_template,
        socio_economic_template)
})

# Create download handler
output$template <- downloadHandler(filename = function(){
  paste0(Sys.Date(), "_risk_score_template.csv")
}, 
content = function(file){
  write.csv(template_data(), file, row.names = F)
})

renderDataTable({
  template_data()
})
```



Column {data-width=200}
--------------------------------------------------------------------------------

#### Download template

```{r}
# Download button --------------------------------------------------------------
output$download_button <- renderUI({downloadButton(outputId = "template",
                                                    label = "Download .csv")})
uiOutput("download_button")
```

Data upload {data-navmenu="Risk tool visualiser" data-icon="fa-upload"}
================================================================================

Column
--------------------------------------------------------------------------------
#### Data upload

```{r}
# Upload button
fileInput(inputId = "upload",
          label = "Upload hazard scores:",
          accept = ".xlsx")

# Store upload in reactive value
hazard_scores <- reactiveValues(scores = NULL)

# Load data
observe({
  # Ensure upload has been set
  req(input$upload)
  
  # Read file
  file <- readxl::read_xlsx(path = input$upload$datapath)
  
  # Convert to data table
  file <- data.table(file)
  
  # Assign to reactive value
  hazard_scores$scores <- file
})

```

Risk visualiser {data-navmenu="Risk tool visualiser" data-icon="fa-chart-pie"}
================================================================================

Column {data-width=350 .sidebar}
-----------------------------------------------------------------------

```{r}
# First input selector
# View by sector or by hazard category
selectInput(inputId = "type",
            label = "Type",
            choices = c("Hazard overview",
                        "Hazard category"))

# Second input selectors -------------------------------------------------------

# Options for hazard category
output$category <- renderUI({
  if(input$type == "Hazard category")
    selectInput(inputId = "category",
                label = "Hazard category",
                choices = c("Biological",
                            "Chemical",
                            "Physical",
                            "Socio-economic"))
})

# Display by sector or impact
output$fill <- renderUI({
  if(input$type %in% c("Hazard overview", "Hazard category")){
    selectInput(inputId = "fill",
                label = "Fill by sector or impact",
                choices = c("Sector",
                            "Impact"))
  }
})

# Render UIs
uiOutput("category")
uiOutput("fill")
```

Column {data-width=650 .tabset}
-----------------------------------------------------------------------

### Plot

```{r}
# Edit synthetic data

updated_data <- reactive({
  if(input$type == "Hazard category"){
    if(input$fill == "Sector"){
      hazard_scores$scores[Category %in% input$category][, .(Score = sum(Score)), by = c("Sector", "Hazard")]
    } else if(input$fill == "Impact"){
      hazard_scores$scores[Category %in% input$category][, .(Score = sum(Score)), by = c("Impact", "Hazard")]
    }
  } else if(input$type == "Hazard overview"){
    if(input$fill == "Sector"){
      hazard_scores$scores[, .(Score = sum(Score)), by = c("Category", "Sector")]
    } else if(input$fill == "Impact"){
      hazard_scores$scores[, .(Score = sum(Score)), by = c("Category", "Impact")]
    }
  }
})


# Colour palettes --------------------------------------------------------------

## Sector =====

sector_cols <- c("#56B4E9",
                          "#009E73",
                          "#0072B2",
                          "#F0E442")
                          
names(sector_cols) <- c("Aquaculture",
                        "Crops",
                        "Fisheries",
                        "Livestock")

## Hazard category =====

category_cols <- c("#CC6677",
                            "#44AA99",
                            "#6699CC",
                            "#AA4499")
                            
names(category_cols) <- c("Biological",
                          "Chemical",
                          "Physical",
                          "Socio-economic")

## Impact ====

impact_cols <- c("#DDCC77",
                          "#882255",
                          "#117733",
                          "#88CCEE")
                          
names(impact_cols) <- c("Food production",
                        "Human health",
                        "Natural environment",
                        "Climate change")

# Plots
of_plot <- reactive({
  if(input$type == "Hazard category" &&
     input$fill == "Sector"){
    ggplot(data = updated_data()) +
      geom_bar(aes(x = str_wrap(Hazard, 5), y = Score, fill = Sector), 
               col = "white",
               stat = "identity") +
      scale_fill_manual(values = sector_cols) +
      scale_colour_manual(values = sector_cols) +
      xlab("\nCategory") +
      ylab("Hazard score\n") +
      theme_light() +
      theme(legend.position = "bottom",
            text = element_text(size = 20))
  } else if(input$type == "Hazard category" &&
            input$fill == "Impact"){
    ggplot(data = updated_data()) +
      geom_bar(aes(x = str_wrap(Hazard, 5), y = Score, fill = Impact), 
               col = "white",
               stat = "identity") +
      scale_fill_manual(values = impact_cols) +
      scale_colour_manual(values = impact_cols) +
      xlab("\nCategory") +
      ylab("Hazard score\n") +
      theme_light() +
      theme(legend.position = "bottom",
            text = element_text(size = 20))
  } else if(input$type == "Hazard overview" &&
            input$fill == "Sector"){
    ggplot(data = updated_data()) +
      geom_bar(aes(x = Category, y = Score, fill = Sector), 
               col = "white",
               stat = "identity") +
      scale_fill_manual(values = sector_cols) +
      scale_colour_manual(values = sector_cols) +
      xlab("\nCategory") +
      ylab("Hazard score\n") +
      theme_light() +
      ggtitle("Hazard categories by sector") +
      theme(legend.position = "bottom",
            text = element_text(size = 20))
  } else if(input$type == "Hazard overview" &&
            input$fill == "Impact"){
    ggplot(data = updated_data()) +
      geom_bar(aes(x = Category, y = Score, fill = Impact), 
               col = "white",
               stat = "identity") +
      scale_fill_manual(values = impact_cols) +
      scale_colour_manual(values = impact_cols) +
      xlab("\nCategory") +
      ylab("Hazard score\n") +
      theme_light() +
      ggtitle("Hazard categories by impact") +
      theme(legend.position = "bottom",
            text = element_text(size = 20))
  }
})

# Plot
renderPlot({
  of_plot()
})
```

### Data

```{r}
renderDataTable({
  updated_data()
})
```

